### ISSUE TITLE
Way to change fonts in theme?

### ISSUE THREAD

**Issue by aronvandepol** [jonaspleyer/peace-of-posters#2]
Allowing for customizing the font of headers and text independently would be nice. 

This would for example allow Serif + Sans serif font combinations would be nice!

I have tried writing a macro for the problem, but perhaps having some options in the theme for fonts. (assuming this can not be done easier with plain typst)

**Comment by aronvandepol** [comment]
my bad. I just realized this is possible with: 

`heading-text-args` and `body-text-args`. Closed.

**Comment by jonaspleyer** [comment]
Thanks anyways for the question. Do you think that the documentation should be clearer about this?

**Comment by aronvandepol** [comment]
Updating the documentation might help clarify it. This partly explains why I missed it. It was not in the themes documentation but was used in the examples. 

See my proposed documentation update #3

**Comment by jonaspleyer** [comment]
I have merged your proposed changes. Thanks for the feedback. Feel free to contact me again if you need anything else.
